# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    cache_adapter: cache.adapter.apcu
    clientId: '%env(CLIENT_ID)%'
    clientSecret: '%env(CLIENT_SECRET)%'
    urlAuthorize: '%env(ENDPOINT_ROOT)%/trustedx-authserver/oauth/izenpe'
    urlAccessToken: '%env(ENDPOINT_ROOT)%/trustedx-authserver/oauth/izenpe/token'
    urlResourceOwnerDetails: '%env(ENDPOINT_ROOT)%/trustedx-resources/openid/v1/users/me'
    redirectUri: 'app_giltza'
    mailerFrom: "%env(MAILER_FROM)%"
    mailerSendBcc: "%env(bool:MAILER_SEND_BCC)%"
    mailerBCC: "%env(MAILER_BCC)%"
    giltzaLogoutRedirectRoute: 'app_active_activitys'
    giltzaSuccessLoginRedirectRoute: 'app_register_new'
    receiptApiUrl: '%env(RECEIPT_API_URL)%%env(RECEIPT_API_NEW_RECEIPT_URL)%'
    receiptApiUser: '%env(RECEIPT_API_USER)%'
    receiptApiPassword: '%env(RECEIPT_API_PASSWORD)%'
    accountingConceptServiceUrl: '%env(RECEIPT_API_URL)%%env(RECEIPT_API_ACCOUNTING_CONCEPT_URL)%'
    createReceiptsOnConfirmation: '%env(bool:CREATE_RECEIPT_ON_CONFIRMATION)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Psr\Log\LoggerInterface $mdLogger: '@monolog.logger.markdown'

    Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']

    ldap:
        alias: Symfony\Component\Ldap\Ldap
            
    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
            -   host: '%env(LDAP_HOST)%'
                port: '%env(LDAP_PORT)%'
                encryption: none
                options:
                    protocol_version: 3
                    referrals: false    